# -*- coding: utf-8 -*-
"""analises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TExjxWeTscBXiX9gFyY8dLECg47xuPRs
"""

# ============================================================
# FASE 5 - PBL
# MONITOR INTELIGENTE DE TRANSPORTE PÚBLICO
#
# 2º DESAFIO - ANÁLISE ESTATÍSTICA E INVESTIGAÇÃO DOS DADOS
# ============================================================
#
# Base de entrada:
# base_onibus_autonomos_cidade_alfa_refinada.xlsx
#
# Objetivos:
# 1. Estatística descritiva
# 2. Amostragem
# 3. Testes de hipóteses
# 4. Correlações
# 5. Comparações por tráfego, chuva, linha e pontualidade
# 6. Geração de tabelas e gráficos para apoiar o relatório
#
# Nível de significância adotado:
# alpha = 0.05
# ============================================================


# ============================================================
# 1. BIBLIOTECAS
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy import stats

# Ajuste para definir 'display' fora e dentro de ambientes Jupyter/Colab
try:
    from IPython.display import display
except ImportError:
    display = print

# Ajuste para importar 'google.colab' sem aviso no VS Code local
try:
    from google.colab import files  # type: ignore
except ImportError:
    class DummyFiles:
        def upload(self):
            print("Ambiente local detectado.")
            caminho = input("Informe o caminho do arquivo [.xlsx]: ").strip()
            if not caminho:
                caminho = "base_onibus_autonomos_cidade_alfa_refinada.xlsx"
            return {caminho: None}
        def download(self, filename):
            print(f"Arquivo salvo localmente em: {filename}")
    files = DummyFiles()


# ============================================================
# 2. CONFIGURAÇÕES
# ============================================================

ALPHA = 0.05

print("=" * 70)
print("ANÁLISE ESTATÍSTICA - MONITOR INTELIGENTE DE TRANSPORTE PÚBLICO")
print("=" * 70)


# ============================================================
# 3. UPLOAD DA BASE REFINADA
# ============================================================

print("\nFaça o upload da base refinada:")
uploaded = files.upload()

arquivo = list(uploaded.keys())[0]

print("Arquivo carregado:", arquivo)


# ============================================================
# 4. LEITURA DA BASE
# ============================================================

df = pd.read_excel(
    arquivo,
    sheet_name="Base_Refinada"
)

print("\nBase carregada.")
print("Registros:", len(df))
print("Colunas:", len(df.columns))


# ============================================================
# 5. CONFIGURAÇÃO DE TIPOS
# ============================================================

# Garantir que as principais variáveis sejam numéricas
colunas_numericas = [
    "tempo_previsto_min",
    "tempo_real_min",
    "atraso_min",
    "atraso_calculado_min",
    "desvio_tempo_pct",
    "distancia_km",
    "numero_paradas",
    "velocidade_media_kmh",
    "capacidade_passageiros",
    "passageiros_transportados",
    "ocupacao_pct",
    "ocupacao_calculada_pct",
    "consumo_energia_kwh",
    "consumo_kwh_km",
    "consumo_kwh_por_passageiro",
    "tempo_interrupcao_min"
]

for coluna in colunas_numericas:
    if coluna in df.columns:
        df[coluna] = pd.to_numeric(
            df[coluna],
            errors="coerce"
        )


# ============================================================
# 6. CONHECIMENTO INICIAL DA BASE
# ============================================================

print("\n" + "=" * 70)
print("6. VISÃO GERAL")
print("=" * 70)

display(df.head())

print("\nDimensão:")
print(df.shape)

print("\nTipos:")
df.info()


# ============================================================
# 7. ESTATÍSTICA DESCRITIVA
# ============================================================

print("\n" + "=" * 70)
print("7. ESTATÍSTICA DESCRITIVA")
print("=" * 70)

variaveis_descritivas = [
    "tempo_previsto_min",
    "tempo_real_min",
    "atraso_calculado_min",
    "desvio_tempo_pct",
    "distancia_km",
    "numero_paradas",
    "velocidade_media_kmh",
    "passageiros_transportados",
    "ocupacao_pct",
    "consumo_energia_kwh",
    "consumo_kwh_km",
    "tempo_interrupcao_min"
]

variaveis_descritivas = [
    col for col in variaveis_descritivas
    if col in df.columns
]

estatistica = df[variaveis_descritivas].describe().T

estatistica["mediana"] = (
    df[variaveis_descritivas]
    .median()
)

estatistica["variancia"] = (
    df[variaveis_descritivas]
    .var()
)

estatistica["coeficiente_variacao_pct"] = (
    df[variaveis_descritivas].std()
    / df[variaveis_descritivas].mean()
) * 100

estatistica = estatistica.round(2)

display(estatistica)


# ============================================================
# 8. AMOSTRAGEM
# ============================================================

print("\n" + "=" * 70)
print("8. AMOSTRAGEM")
print("=" * 70)

# Amostra aleatória simples de 10%
tamanho_amostra = max(
    30,
    int(len(df) * 0.10)
)

amostra = df.sample(
    n=tamanho_amostra,
    random_state=42
)

print("Tamanho da população:", len(df))
print("Tamanho da amostra:", len(amostra))

display(
    amostra[
        [
            col for col in [
                "id_viagem",
                "linha",
                "atraso_calculado_min",
                "nivel_trafego",
                "chuva",
                "passageiros_transportados",
                "ocupacao_pct"
            ]
            if col in amostra.columns
        ]
    ].head(10)
)


# Comparar média da população e da amostra
if "atraso_calculado_min" in df.columns:

    media_populacao_atraso = (
        df["atraso_calculado_min"].mean()
    )

    media_amostra_atraso = (
        amostra["atraso_calculado_min"].mean()
    )

    print("\nMédia do atraso - população:",
          round(media_populacao_atraso, 2))

    print("Média do atraso - amostra:",
          round(media_amostra_atraso, 2))


# ============================================================
# 9. INTERVALO DE CONFIANÇA DA MÉDIA DO ATRASO
# ============================================================

print("\n" + "=" * 70)
print("9. INTERVALO DE CONFIANÇA")
print("=" * 70)

if "atraso_calculado_min" in df.columns:

    dados_atraso = (
        df["atraso_calculado_min"]
        .dropna()
    )

    n = len(dados_atraso)
    media = dados_atraso.mean()
    erro_padrao = stats.sem(dados_atraso)

    intervalo = stats.t.interval(
        confidence=0.95,
        df=n - 1,
        loc=media,
        scale=erro_padrao
    )

    print(
        f"Média do atraso: {media:.2f} min"
    )

    print(
        f"IC 95%: [{intervalo[0]:.2f}, "
        f"{intervalo[1]:.2f}] min"
    )


# ============================================================
# 10. CORRELAÇÃO
# ============================================================

print("\n" + "=" * 70)
print("10. ANÁLISE DE CORRELAÇÃO")
print("=" * 70)

pares_correlacao = [
    ("atraso_calculado_min", "tempo_real_min"),
    ("atraso_calculado_min", "distancia_km"),
    ("atraso_calculado_min", "numero_paradas"),
    ("atraso_calculado_min", "velocidade_media_kmh"),
    ("atraso_calculado_min", "ocupacao_pct"),
    ("atraso_calculado_min", "consumo_energia_kwh"),
    ("passageiros_transportados", "consumo_energia_kwh"),
    ("distancia_km", "consumo_energia_kwh"),
    ("ocupacao_pct", "consumo_kwh_por_passageiro")
]

resultados_correlacao = []

for x, y in pares_correlacao:

    if x not in df.columns or y not in df.columns:
        continue

    dados = df[[x, y]].dropna()

    if len(dados) < 3:
        continue

    pearson_r, pearson_p = stats.pearsonr(
        dados[x],
        dados[y]
    )

    spearman_r, spearman_p = stats.spearmanr(
        dados[x],
        dados[y]
    )

    resultados_correlacao.append({
        "variavel_x": x,
        "variavel_y": y,
        "pearson_r": round(pearson_r, 4),
        "pearson_p": round(pearson_p, 6),
        "spearman_r": round(spearman_r, 4),
        "spearman_p": round(spearman_p, 6)
    })

correlacoes = pd.DataFrame(
    resultados_correlacao
)

display(correlacoes)


# ============================================================
# 11. TESTE DE HIPÓTESE 1
#    CHUVA x ATRASO
#
# H0: a média de atraso é igual em dias com e sem chuva.
# H1: a média de atraso é diferente.
# ============================================================

print("\n" + "=" * 70)
print("11. TESTE DE HIPÓTESE - CHUVA x ATRASO")
print("=" * 70)

if {
    "chuva",
    "atraso_calculado_min"
}.issubset(df.columns):

    grupo_sem_chuva = (
        df.loc[
            df["chuva"] == "Não",
            "atraso_calculado_min"
        ]
        .dropna()
    )

    grupo_com_chuva = (
        df.loc[
            df["chuva"] == "Sim",
            "atraso_calculado_min"
        ]
        .dropna()
    )

    print("Média sem chuva:",
          round(grupo_sem_chuva.mean(), 2))

    print("Média com chuva:",
          round(grupo_com_chuva.mean(), 2))

    # Teste de Welch, adequado quando as variâncias podem diferir
    t_stat, p_valor = stats.ttest_ind(
        grupo_sem_chuva,
        grupo_com_chuva,
        equal_var=False
    )

    print("\nt =", round(t_stat, 4))
    print("p-valor =", round(p_valor, 6))

    if p_valor < ALPHA:
        print(
            "Conclusão: rejeitamos H0. "
            "Há evidência de diferença estatisticamente "
            "significativa entre os grupos."
        )
    else:
        print(
            "Conclusão: não rejeitamos H0. "
            "Não há evidência estatística suficiente "
            "de diferença entre os grupos."
        )


# ============================================================
# 12. TESTE DE HIPÓTESE 2
#     NÍVEL DE TRÁFEGO x ATRASO
#
# H0: as médias de atraso são iguais nos níveis de tráfego.
# H1: pelo menos um grupo apresenta média diferente.
# ============================================================

print("\n" + "=" * 70)
print("12. TESTE DE HIPÓTESE - TRÁFEGO x ATRASO")
print("=" * 70)

if {
    "nivel_trafego",
    "atraso_calculado_min"
}.issubset(df.columns):

    grupos_trafego = []

    for nivel in ["Baixo", "Moderado", "Alto"]:

        grupo = (
            df.loc[
                df["nivel_trafego"] == nivel,
                "atraso_calculado_min"
            ]
            .dropna()
        )

        print(
            f"Média de atraso - {nivel}: "
            f"{grupo.mean():.2f} min"
        )

        grupos_trafego.append(grupo)

    # ANOVA de uma via
    f_stat, p_valor_anova = stats.f_oneway(
        *grupos_trafego
    )

    print("\nF =", round(f_stat, 4))
    print("p-valor =", round(p_valor_anova, 6))

    if p_valor_anova < ALPHA:
        print(
            "Conclusão: rejeitamos H0. "
            "Existe diferença estatisticamente significativa "
            "entre pelo menos dois níveis de tráfego."
        )
    else:
        print(
            "Conclusão: não rejeitamos H0. "
            "Não foi identificada diferença estatística "
            "suficiente entre os níveis de tráfego."
        )


# ============================================================
# 13. TESTE DE HIPÓTESE 3
#     LINHAS COMPARADAS PELO ATRASO
#
# Uso: identificar linhas com comportamento diferente.
# Não testamos todas as linhas entre si; selecionamos
# as linhas com maior volume de viagens.
# ============================================================

print("\n" + "=" * 70)
print("13. COMPARAÇÃO DE DESEMPENHO ENTRE LINHAS")
print("=" * 70)

if {
    "linha",
    "atraso_calculado_min"
}.issubset(df.columns):

    linhas_frequentes = (
        df["linha"]
        .value_counts()
        .head(5)
        .index
        .tolist()
    )

    dados_linhas = []

    for linha in linhas_frequentes:

        valores = (
            df.loc[
                df["linha"] == linha,
                "atraso_calculado_min"
            ]
            .dropna()
        )

        dados_linhas.append(valores)

        print(
            f"{linha}: "
            f"n={len(valores)} | "
            f"média={valores.mean():.2f} min | "
            f"mediana={valores.median():.2f} min"
        )

    if len(dados_linhas) >= 2:

        f_linhas, p_linhas = stats.f_oneway(
            *dados_linhas
        )

        print("\nANOVA entre as 5 linhas com maior volume")
        print("F =", round(f_linhas, 4))
        print("p-valor =", round(p_linhas, 6))

        if p_linhas < ALPHA:
            print(
                "Conclusão: há evidência de diferenças "
                "estatisticamente significativas entre as médias."
            )
        else:
            print(
                "Conclusão: não há evidência estatística suficiente "
                "de diferença entre as médias."
            )


# ============================================================
# 14. PONTUALIDADE
# ============================================================

print("\n" + "=" * 70)
print("14. INDICADORES DE PONTUALIDADE")
print("=" * 70)

if "status_pontualidade" in df.columns:

    contagem_pontualidade = (
        df["status_pontualidade"]
        .value_counts(dropna=False)
    )

    percentual_pontualidade = (
        df["status_pontualidade"]
        .value_counts(normalize=True, dropna=False)
        * 100
    )

    tabela_pontualidade = pd.DataFrame({
        "quantidade": contagem_pontualidade,
        "percentual": percentual_pontualidade.round(2)
    })

    display(tabela_pontualidade)

    if "No horário" in percentual_pontualidade.index:

        print(
            "Percentual de viagens no horário:",
            round(
                percentual_pontualidade["No horário"],
                2
            ),
            "%"
        )


# ============================================================
# 15. FALHAS E INTERRUPÇÕES
# ============================================================

print("\n" + "=" * 70)
print("15. FALHAS E INTERRUPÇÕES")
print("=" * 70)

if "tipo_falha" in df.columns:

    falhas = (
        df["tipo_falha"]
        .value_counts()
    )

    display(falhas.to_frame("quantidade"))

if "tempo_interrupcao_min" in df.columns:

    viagens_interrompidas = (
        df["tempo_interrupcao_min"] > 0
    ).sum()

    taxa_interrupcao = (
        viagens_interrompidas
        /
        len(df)
    ) * 100

    print(
        "Viagens com interrupção:",
        viagens_interrompidas
    )

    print(
        "Taxa de interrupção:",
        round(taxa_interrupcao, 2),
        "%"
    )


# ============================================================
# 16. UTILIZAÇÃO DA FROTA
# ============================================================

print("\n" + "=" * 70)
print("16. UTILIZAÇÃO DA FROTA")
print("=" * 70)

colunas_frota = [
    col for col in [
        "id_onibus",
        "passageiros_transportados",
        "ocupacao_pct",
        "atraso_calculado_min",
        "consumo_kwh_km"
    ]
    if col in df.columns
]

if {
    "id_onibus",
    "passageiros_transportados"
}.issubset(df.columns):

    desempenho_frota = (
        df.groupby("id_onibus")
        .agg(
            viagens=("id_viagem", "count"),
            passageiros=("passageiros_transportados", "sum"),
            media_ocupacao=("ocupacao_pct", "mean"),
            media_atraso=("atraso_calculado_min", "mean"),
            media_consumo_km=("consumo_kwh_km", "mean")
        )
        .sort_values(
            "media_ocupacao",
            ascending=False
        )
    )

    display(
        desempenho_frota
        .round(2)
        .head(10)
    )


# ============================================================
# 17. ANÁLISE POR PERÍODO DO DIA
# ============================================================

print("\n" + "=" * 70)
print("17. DESEMPENHO POR PERÍODO DO DIA")
print("=" * 70)

if {
    "periodo_dia",
    "atraso_calculado_min"
}.issubset(df.columns):

    desempenho_periodo = (
        df.groupby("periodo_dia", observed=True)
        .agg(
            viagens=("id_viagem", "count"),
            atraso_medio=("atraso_calculado_min", "mean"),
            velocidade_media=("velocidade_media_kmh", "mean"),
            ocupacao_media=("ocupacao_pct", "mean")
        )
        .round(2)
    )

    display(desempenho_periodo)


# ============================================================
# 18. VISUALIZAÇÃO 1 - DISTRIBUIÇÃO DO ATRASO
# ============================================================

if "atraso_calculado_min" in df.columns:

    plt.figure(figsize=(10, 5))

    plt.hist(
        df["atraso_calculado_min"].dropna(),
        bins=30
    )

    plt.title(
        "Distribuição do Atraso Calculado"
    )

    plt.xlabel(
        "Atraso (minutos)"
    )

    plt.ylabel(
        "Quantidade de viagens"
    )

    plt.grid(alpha=0.2)

    plt.show()


# ============================================================
# 19. VISUALIZAÇÃO 2 - ATRASO POR TRÁFEGO
# ============================================================

if {
    "nivel_trafego",
    "atraso_calculado_min"
}.issubset(df.columns):

    medias_trafego = (
        df.groupby("nivel_trafego")[
            "atraso_calculado_min"
        ]
        .mean()
        .reindex(["Baixo", "Moderado", "Alto"])
    )

    plt.figure(figsize=(8, 5))

    medias_trafego.plot(
        kind="bar"
    )

    plt.title(
        "Atraso Médio por Nível de Tráfego"
    )

    plt.xlabel(
        "Nível de tráfego"
    )

    plt.ylabel(
        "Atraso médio (minutos)"
    )

    plt.xticks(rotation=0)

    plt.tight_layout()

    plt.show()


# ============================================================
# 20. VISUALIZAÇÃO 3 - CHUVA x ATRASO
# ============================================================

if {
    "chuva",
    "atraso_calculado_min"
}.issubset(df.columns):

    medias_chuva = (
        df.groupby("chuva")[
            "atraso_calculado_min"
        ]
        .mean()
        .reindex(["Não", "Sim"])
    )

    plt.figure(figsize=(8, 5))

    medias_chuva.plot(
        kind="bar"
    )

    plt.title(
        "Atraso Médio em Condições de Chuva"
    )

    plt.xlabel(
        "Chuva"
    )

    plt.ylabel(
        "Atraso médio (minutos)"
    )

    plt.xticks(rotation=0)

    plt.tight_layout()

    plt.show()


# ============================================================
# 21. VISUALIZAÇÃO 4 - DISTÂNCIA x ATRASO
# ============================================================

if {
    "distancia_km",
    "atraso_calculado_min"
}.issubset(df.columns):

    plt.figure(figsize=(10, 5))

    plt.scatter(
        df["distancia_km"],
        df["atraso_calculado_min"],
        alpha=0.5
    )

    plt.title(
        "Relação entre Distância e Atraso"
    )

    plt.xlabel(
        "Distância (km)"
    )

    plt.ylabel(
        "Atraso (minutos)"
    )

    plt.grid(alpha=0.2)

    plt.show()


# ============================================================
# 22. MATRIZ DE CORRELAÇÃO
# ============================================================

print("\n" + "=" * 70)
print("22. MATRIZ DE CORRELAÇÃO")
print("=" * 70)

variaveis_matriz = [
    "tempo_previsto_min",
    "tempo_real_min",
    "atraso_calculado_min",
    "distancia_km",
    "numero_paradas",
    "velocidade_media_kmh",
    "passageiros_transportados",
    "ocupacao_pct",
    "consumo_energia_kwh",
    "consumo_kwh_km"
]

variaveis_matriz = [
    col for col in variaveis_matriz
    if col in df.columns
]

matriz_correlacao = (
    df[variaveis_matriz]
    .corr(method="pearson")
    .round(2)
)

display(matriz_correlacao)


# ============================================================
# 23. EXPORTAR RESULTADOS
# ============================================================

nome_saida = (
    "resultados_analise_estatistica_onibus.xlsx"
)

with pd.ExcelWriter(
    nome_saida,
    engine="openpyxl"
) as writer:

    estatistica.to_excel(
        writer,
        sheet_name="Descritiva"
    )

    correlacoes.to_excel(
        writer,
        sheet_name="Correlacoes",
        index=False
    )

    matriz_correlacao.to_excel(
        writer,
        sheet_name="Matriz_Correlacao"
    )

    if "status_pontualidade" in df.columns:

        tabela_pontualidade.to_excel(
            writer,
            sheet_name="Pontualidade"
        )

    if {
        "id_onibus",
        "passageiros_transportados"
    }.issubset(df.columns):

        desempenho_frota.to_excel(
            writer,
            sheet_name="Frota"
        )

    if {
        "periodo_dia",
        "atraso_calculado_min"
    }.issubset(df.columns):

        desempenho_periodo.to_excel(
            writer,
            sheet_name="Periodo"
        )


# ============================================================
# 24. SALVAR O CÓDIGO/RESULTADOS
# ============================================================

print("\n" + "=" * 70)
print("ANÁLISE CONCLUÍDA")
print("=" * 70)

print(
    "Arquivo de resultados gerado:",
    nome_saida
)

files.download(nome_saida)

print(
    "\nOs resultados acima devem ser interpretados como "
    "evidências estatísticas da base simulada."
)

print(
    "Correlação e significância estatística não implicam "
    "causalidade."
)